language: scala
scala:
   - 2.11.11

jdk:
   - openjdk8

before_install:
   - sudo apt-get install python3 python3-pip python3-numpy python3-setuptools realpath

install:
   - source ./scripts/install-jep.sh

env:
   - POLYNOTE_DEBUG=true

cache:
   directories:
      - $HOME/.cache/pip
      - $HOME/.sbt
      - $HOME/.ivy2
      - $HOME/.m2
      - $HOME/.local/lib/python3.4/site-packages