language: scala
scala:
   - 2.11.11

jdk:
   - openjdk8

before_install:
  - pyenv global 3.7.1
  - pip install virtualenv ipython nbconvert jedi numpy scipy pyspark==2.1.2 jep==3.8.2
  - jep_site_packages_path=`pip show jep | grep "^Location:" | cut -d ':' -f 2 | cut -d ' ' -f 2`
  - jep_path=${jep_site_packages_path}/jep
  - jep_lib_path=`realpath ${jep_site_packages_path}/../../`
  - export LD_LIBRARY_PATH=${jep_path}:${jep_site_packages_path}:${jep_lib_path}:${LD_LIBRARY_PATH}
  - echo ${LD_LIBRARY_PATH}
  - export LD_PRELOAD=${jep_lib_path}/libpython3.so
  - echo ${LD_PRELOAD}

env:
   - POLYNOTE_DEBUG=true

cache:
   directories:
      - $HOME/.cache/pip
      - $HOME/.sbt
      - $HOME/.ivy2
      - $HOME/.m2
      - $HOME/.local/lib/python3.4/site-packages