language: scala
scala:
   - 2.11.11

jdk:
   - openjdk8

before_install:
  - pyenv versions
  - python --version
  - pip --version
  - python3 --version
  - pip3 install jep ipython nbconvert jedi numpy scipy pyspark==2.1.2

env:
   - POLYNOTE_DEBUG=true

cache:
   directories:
      - $HOME/.cache/pip
      - $HOME/.sbt
      - $HOME/.ivy2
      - $HOME/.m2
      - $HOME/.local/lib/python3.4/site-packages