language: scala
scala:
   - 2.11.11

before_install:
   - sudo apt-get install python3 python3-pip python3-numpy

install:
   - pip3 install --user jep ipython nbconvert
   - export LD_LIBRARY_PATH=`pip3 show jep |grep "^Location:" |cut -d ':' -f 2 |cut -d ' ' -f 2`/jep:$LD_LIBRARY_PATH

cache:
   directories:
      - $HOME/.cache/pip
      - $HOME/.sbt
      - $HOME/.ivy2