# The host and port can be set by uncommenting and editing the following lines:
#listen:
#  host: 0.0.0.0
#  port: 8192

# The location Polynote looks for your notebooks in
#storage:
#  dir: notebooks

# Default repositories can be specified. Uncommenting the following lines would add four default repositories which are inherited by new notebooks.
#repositories:
#  - ivy:
#      base: https://my-artifacts.org/artifacts/
#  - ivy:
#      base: https://my-custom-ivy-repo.org/artifacts/
#      artifact_pattern: [orgPath]/[module](_[scalaVersion])(_[sbtVersion])/[revision]/[artifact]-[revision](-[classifier]).[ext]
#      metadata_pattern: [orgPath]/[module](_[scalaVersion])(_[sbtVersion])/[revision]/[module](_[scalaVersion])(_[sbtVersion])-[revision]-ivy.xml
#      changing: true
#  - maven:
#      base: http://central.maven.org/maven2/
#  - maven:
#      base: http://oss.sonatype.org/content/repositories/snapshots
#      changing: true

# Default dependencies can be specified. Uncommenting the following lines would add default dependencies for the Scala interpreter, which are inherited by new notebooks.
#dependencies:
#  scala:
#    - org.typelevel:cats-core_2.11:1.6.0
#    - com.mycompany:my-library:jar:all:1.0.0

#exclusions:
#  - com.google.guava:guava  # spark, update your guava already!!!

# Spark config params can be set by uncommenting and editing the following lines:
#spark:
#  spark.driver.userClasspathFirst: true
#  spark.executor.userClasspathFirst: true
