name: Docs

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps: [{
              name: 'Trigger docs repo update',
              uses: defold/repository-dispatch@1.1.4,
              with: {
                repo: 'polynote/polynote.github.io',
                token: '${{ secrets.GITHUB_TOKEN }}',
                action: 'update-docs'
              }
            }]